name: c4_tools
description: "C4 Tools"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  pointycastle: ^3.9.1
  http: ^1.4.0
  xterm: ^4.0.0
  dartssh2: ^2.12.0
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  flutter_inappwebview: ^6.2.0-beta.2 #not supported on linux currently
  path_provider: ^2.1.5
  archive: ^4.0.7
  path: ^1.9.1
  url_launcher: ^6.2.5
  xml: ^6.5.0
  window_manager: ^0.5.0 #desktop only
  open_file: ^3.5.10
  android_intent_plus: ^5.3.0
  file_picker: ^10.1.9
  version: ^3.0.2

dev_dependencies:
  package_rename: ^1.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ssl/openssl.cfg
    - assets/icon/icon.png
